<?php
    $_layout = $this->getLayout();
    $_dob    = $_layout->createBlock('customer/widget_dob');
    $_gender = $_layout->createBlock('customer/widget_gender');
    $_taxvat = $_layout->createBlock('customer/widget_taxvat');
    $_isCustomerLoggedIn = $this->isCustomerLoggedIn();
    $_address = Mage::getModel('sales/quote_address');
	$customer = null;//Mage::getSingleton('customer/session')->getCustomer();
    $_prefix  = 'billing';

	$typeperson = Mage::getStoreConfig('firecheckout/general/typeperson_enabled');

    $status = Mage::getStoreConfig('firecheckout/address_form_status');
    if ('hidden' !== $status['postcode']) {
        $status['postcode'] = 'required'; // used to render asterisk
    }
    if (Mage::getStoreConfig('general/region/state_required')) {
        //$status['region'] = 'required'; // used to render asterisk
    }

    $fields = array(
        'name'  => array(),
        'email' => array(
            'class'  => 'input-text validate-email',
            'label'  => 'Email Address',
            'status' => $_isCustomerLoggedIn ? 'hidden' : 'required',
            'class_label' => ''
        ),
        'company' => array(
            'class' => 'input-text company',
            'label' => 'Company',
            'class_label' => ''
        ),
        'fax' => array(
            'class' => 'input-text fax ',
            'label' => 'Fax',
            'class_label' => ''
        ),
        'telephone' => array(
            'class' => 'input-text telephone',
            'label' => 'Telephone',
            'class_label' => ''
        ),
        'city' => array(
            'class' => 'input-text city',
            'label' => 'City',
            'class_label' => ''
        ),
        'postcode' => array(
            'class' => 'input-text validate-zip-international validate-number postcode',
            'label' => 'Zip/Postal Code',
            'class_label' => ''
        ),
        'street1' => array(
            'class' => 'input-text',
            'title1' => 'Street Address',
            'title2' => 'Number Address',
            'title3' => 'Extend Address',
            'title4' => 'Neighborhood',
            'class_label' => ''
        ),
        'country_id' => array(
            'label' => 'Country',
            'required_to_render' => 1,
            'class_label' => ''
        ),
        'region' => array(
            'label' => 'State/Province',
            'required_to_render' => 1,
            'class' => 'region',
            'class_label' => ''
        ),
        'dob' => array(
            'status' => ($_dob->isEnabled()) ? 'optional' : 'hidden',
            'class_label' => ''
        ),
        'gender' => array(
            'status' => ($_gender->isEnabled()) ? 'optional' : 'hidden',
            'class_label' => ''
        ),
        'taxvat' => array(
            'status' => ($_taxvat->isEnabled()) ? 'optional' : 'hidden',
            'class_label' => ''
        ),
        'rg' => array(
        	'label' => 'R.G.',
            'status' =>  Mage::getStoreConfig('firecheckout/address_form_status/rg'),
            'class' => 'input-text rg cp_fisica',
            'class_label' => 'cp_fisica'
            )
			,
        'cpfcnpj' => array(
        	'label' => 'CPF/CNPJ',
            'status' =>  Mage::getStoreConfig('firecheckout/address_form_status/cpfcnpj'),
            'class' => 'input-text cpfcnpj validar_cpfcnpj',
            'class_label' => ''
            )
			,
        'ie' => array(
        	'label' => 'I.E.',
            'status' =>  Mage::getStoreConfig('firecheckout/address_form_status/ie'),
            'class' => 'input-text ie cp_juridica',
            'class_label' => 'cp_juridica'
            )
				,
        'empresa' => array(
        	'label' => 'Corporate Name',
            'status' =>  Mage::getStoreConfig('firecheckout/address_form_status/empresa'),
            'class' => 'input-text empresa cp_juridica',
            'class_label' => 'cp_juridica'
            )
			,
		'celular' => array(
        	'label' => 'Mobile Phone',
            'status' =>  Mage::getStoreConfig('firecheckout/address_form_status/celular'),
            'class' => 'input-text celular',
            'class_label' => ''
            )
			,
		'tipopessoa' => array(
        	'label' => 'Type Person',
            'status' =>  Mage::getStoreConfig('firecheckout/address_form_status/tipopessoa'),
            'class' => 'tipopessoa',
            'class_label' => ''
            ),
		'nome_fantasia' => array(
        	'label' => 'Name Fantasy',
        	'class' => 'input-text nome-fantasia cp_juridica',
            'status' =>  Mage::getStoreConfig('firecheckout/address_form_status/nome_fantasia'),
            'class_label' => 'cp_juridica'
            )
    );

    $addressHelper = $this->helper('customer/address');

    if (method_exists($addressHelper, 'isVatAttributeVisible')) {
        $fields['vat_id'] = array(
            'status' => $addressHelper->isVatAttributeVisible() ? 'optional' : 'hidden',
            'class'  => 'input-text ' . $addressHelper->getAttributeValidationClass('vat_id'),
            'label'  => 'VAT Number'
        );
    }

    if($this->customerHasAddresses())
  	{
  		$status['tipopessoa'] = "hidden";
  		$status['nome_fantasia'] = "hidden";
  		$status['celular'] = "hidden";
  		$status['empresa'] = "hidden";
  		$status['ie'] = "hidden";
  		$status['rg'] = "hidden";
  		$status['cpfcnpj'] = "hidden";
      $status['taxvat'] = "hidden";
      $status['gender'] = "hidden";
      $status['dob'] = "hidden";

  	}
?>

<div id="billing-address" class="firecheckout-section">
    <div class="block-content">
        <ul class="form-list">

        <li id="billing-new-address-form">
            <fieldset>
                <ul>
                    <?php foreach (Mage::helper('firecheckout/address')->getSortedFields() as $row) : ?>
                        <?php
                            $countVisible          = 0;
                            $countRequiredToRender = 0;

                            foreach ($row as $key => $field) { // do not use break in this cycle to fill statuses for all fields
                                if (!isset($fields[$field])) { // billing address doesn't have all of the fields
                                    unset($row[$key]);
                                    continue;
                                }

                                if (empty($status[$field])) {
                                    if (!empty($fields[$field]['status'])) {
                                        $status[$field] = $fields[$field]['status'];
                                    } else {
                                        $status[$field] = 'required';
                                    }
                                }
                                if (!empty($fields[$field]['required_to_render'])) {
                                    $countRequiredToRender++;
                                }
                                if ('hidden' !== $status[$field]) {
                                    $countVisible++;
                                }
                            }

                            $isMulticolumn = ($countVisible > 1 || current($row) == 'name');
                        ?>

                        <?php if (!$countVisible && !$countRequiredToRender): continue; endif; ?>

                        <li class="<?php echo $isMulticolumn ? 'fields' : 'wide' ?>"<?php echo $countVisible ? '' : ' style="display: none;"' ?>>
                            <?php foreach ($row as $field) : ?>
                                <?php $required = ('required' === $status[$field]); ?>

                                <?php if ('name' === $field) : ?>
                                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($_address)->setFieldIdFormat($_prefix . ':%s')->setFieldNameFormat($_prefix . '[%s]')->toHtml() ?>
                                <?php else : ?>

                                    <?php if ('hidden' === $status[$field]) :
                                        if (empty($fields[$field]['required_to_render'])) :
                                            continue;
                                        endif; ?>

                                        <div style="display: none;">
                                    <?php endif; ?>

                                    <?php if ($isMulticolumn) : ?>
                                        <div class="field field_<?php echo $field ?>">
                                    <?php endif; ?>

                                    <?php if ('dob' === $field): ?>
                                        <?php echo $_dob->setDate($_address->getDob())->setFieldIdFormat($_prefix . ':%s')->setFieldNameFormat($_prefix . '[%s]')->toHtml() ?>
                                    <?php elseif ('gender' === $field): ?>
                                        <?php echo $_gender->setGender($_address->getGender())->setFieldIdFormat($_prefix . ':%s')->setFieldNameFormat($_prefix . '[%s]')->toHtml() ?>
                                    <?php elseif ('taxvat' === $field): ?>
                                        <?php echo $_taxvat->setTaxvat($_address->getTaxvat())->setFieldIdFormat($_prefix . ':%s')->setFieldNameFormat($_prefix . '[%s]')->toHtml() ?>
                                    <?php elseif ('street1' === $field): ?>
                                    	<?php for ($_i = 1, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                			<div class="field street<?php echo $_i; ?>">
                                				<label for="<?php echo $_prefix ?>:street<?php echo $_i; ?>"  <?php if($_i != 3 ): ?>class="required"  <?php endif; ?>> <?php if($_i != 3 ): ?><em>*</em>  <?php endif; ?><?php echo $this->__($fields[$field]['title'.$_i]); ?></label>
                                				<input type="text"
                                				placeholder="<?php echo $this->__($fields[$field]['title'.$_i]); ?>" 
                                				title="<?php echo $this->__($fields[$field]['title'.$_i]); ?>" name="<?php echo $_prefix ?>[street][]" id="<?php echo $_prefix ?>:street<?php echo $_i?>" value="<?php echo $this->escapeHtml($_address->getStreet($_i)) ?>" class="input-text <?php if($_i != 3 ): ?>required-entry <?php endif; ?>street<?php echo $_i; ?>-input" />
                                			</div>
                                		<?php endfor; ?>
                                	<?php elseif('tipopessoa' === $field): ?>


                                			<div class="field" <?php if($typeperson >=2): ?> style="display:none" <?php endif; ?>>
                                			<label  for="<?php echo $_prefix ?>:<?php echo $field ?>"
	                                            class="<?php echo $required ? 'required' : '' ?>"
	                                            ><?php if ($required): ?><em>*</em><?php endif; ?><?php echo $this->__($fields[$field]['label']) ?></label>
	                                			<select id="<?php echo $_prefix ?>:<?php echo $field; ?>" name="<?php echo $_prefix ?>[<?php echo $field; ?>]" title="<?php echo $this->__($fields[$field]['label']); ?>" <?php if ($required): ?> class="required-entry <?php echo $this->__($fields[$field]['class']); ?>" <?php endif; ?> >
													<?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('tipopessoa')->getSource()->getAllOptions();?>
													<?php foreach ($options as $option):?>
														<option value="<?php echo $option['value'] ?>" <?php if($typeperson == 2 && $option['value'] == 2 || $typeperson == 3 && $option['value'] == 1): ?> selected="selected" <?php endif; ?>><?php echo $option['label'] ?></option>
													<?php endforeach;?>
		    									</select>
		    									</div>


                                    <?php else: ?>
                                        <label for="<?php echo $_prefix ?>:<?php echo $field ?>"
                                            class="<?php echo $required ? 'required' : '' ?> <?php echo $this->__($fields[$field]['class_label']); ?>"
                                            ><?php if ($required): ?><em>*</em><?php endif; ?><?php echo $this->__($fields[$field]['label']) ?></label>
                                        <div class="input-box">
                                            <?php if ('country_id' === $field) : ?>
                                                <?php echo $this->getCountryHtmlSelect($_prefix) ?>
                                            <?php elseif ('region' === $field): ?>
                                                <select id="<?php echo $_prefix ?>:region_id" name="<?php echo $_prefix ?>[region_id]"
                                                    title="<?php echo (empty($fields[$field]['title']) ? $this->__($fields[$field]['label']) : $this->__($fields[$field]['title'])) ?>"
                                                    class="validate-select<?php echo $required ? ' required-entry' : '' ?>" style="display:none;"
                                                >
                                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                                </select>
                                                <script type="text/javascript">
                                                //<![CDATA[
                                                    $('<?php echo $_prefix ?>:region_id').setAttribute('defaultValue',  "<?php echo $_address->getRegionId() ?>");
                                                //]]>
                                                </script>
                                                <input type="text" id="<?php echo $_prefix ?>:region" name="<?php echo $_prefix ?>[region]"
                                                    value="<?php echo $this->escapeHtml($_address->getRegion()) ?>"
                                                    title="<?php echo (empty($fields[$field]['title']) ? $this->__($fields[$field]['label']) : $this->__($fields[$field]['title'])) ?>"
                                                    placeholder="<?php echo (empty($fields[$field]['title']) ? $this->__($fields[$field]['label']) : $this->__($fields[$field]['title'])) ?>"
                                                    class="input-text<?php echo $required ? ' required-entry' : '' ?>" style="display:none;"
                                                />
                                            <?php else: ?>
                                                <?php
                                                    if (isset($fields[$field]['value'])):
                                                        $value = $fields[$field]['value'];
                                                    else:
                                                        $method = 'get' . ucfirst($field);
                                                        $value = $_address->{$method}();
                                                    endif;
                                                ?>
                                                <input type="text"
                                                    name="<?php echo (empty($fields[$field]['name']) ? $_prefix . '[' . $field . ']' : $fields[$field]['name']) ?>"
                                                    id="<?php echo $_prefix ?>:<?php echo $field ?>"
                                                    value="<?php echo $this->escapeHtml($value) ?>"
                                                    title="<?php echo (empty($fields[$field]['title']) ? $this->__($fields[$field]['label']) : $this->__($fields[$field]['title'])) ?>"
                                                    placeholder="<?php echo (empty($fields[$field]['title']) ? $this->__($fields[$field]['label']) : $this->__($fields[$field]['title'])) ?>"
                                                    class="<?php echo $fields[$field]['class'] ?><?php echo $required ? ' required-entry' : '' ?>"
                                                />
                                                <?php if('postcode' === $field): ?>
                                                	<div id="<?php echo $_prefix; ?>loader" class="loader_cep" style="display:none;"></div>
                                                	<a href="http://www.buscacep.correios.com.br/" title="" target="_blank" class="faq8">
                                                		<span class="bubble">Não sei meu cep</span>
                                                	</a>
                                                <?php endif ?>

                                                 <?php if('ie' === $field): ?>
                                                	<a href="#" id="isento" class="faq8 cp_juridica">
                                                		<span class="bubble">Sou isento, clique</span>
                                                	</a>
                                                <?php endif ?>

                                            <?php endif ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($isMulticolumn) : ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ('hidden' === $status[$field]) : ?>
                                        </div>
                                    <?php endif; ?>

                                <?php endif; ?>

                            <?php endforeach; ?>
                        </li>
                    <?php endforeach; ?>

                    <?php $addressAttributes = $this->getChild('customer_form_' . $_prefix . '_address_user_defined_attributes');?>
                    <?php if ($addressAttributes): ?>
                        <?php $addressAttributes->setEntity($_address)->setEntityType('customer_address');?>
                        <?php $addressAttributes->setFieldIdFormat($_prefix . ':%1$s')->setFieldNameFormat($_prefix . '[%1$s]');?>
                        <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
                    <?php endif;?>

                    <?php $customerAttributes = $this->getChild('customer_form_customer_user_defined_attributes');?>
                    <?php if ($customerAttributes): ?>
                        <?php $customerAttributes->setEntityModelClass('customer/customer')->setFieldIdFormat($_prefix . ':%1$s');?>
                        <?php $customerAttributes->setFieldNameFormat($_prefix . '[%1$s]')->setShowContainer(false);?>
                        <?php echo $customerAttributes->setExcludeFileAttributes(true)->toHtml()?>
                    <?php endif;?>

                    <?php if (!$this->isCustomerLoggedIn()) : ?>
                        <?php
                            $registrationMode = Mage::getStoreConfig('firecheckout/general/registration_mode');
                            $register = $this->getRegisterAccount();
                            $isAllowedGuest = Mage::helper('firecheckout')->isAllowedGuestCheckout();
                        if ($isAllowedGuest || $register) : ?>
                            <li class="control">
                                <input type="checkbox" name="billing[register_account]" value="1" title="<?php echo $this->__('Create account for later use') ?>" id="billing:register_account" onclick="if(window.billing) billing.setCreateAccount(this.checked);"<?php if ($register || 'optional-checked' == $registrationMode) : ?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:register_account"><?php echo $this->__('Create account for later use') ?></label>
                            </li>
                        <?php else: ?>
                            <li class="no-display">
                                <input type="hidden" name="billing[register_account]" value="1"/>
                            </li>
                        <?php endif ?>
                        <?php if ('hidden' !== $registrationMode || $register) : ?>
                            <li class="fields" id="register-customer-password" <?php if ('optional' == $registrationMode && !$register) : ?>style="display: none;" <?php endif; ?>>
                                <div class="field">
                                    <label for="billing:customer_password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                                    <div class="input-box">
                                        <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="billing:confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                                    <div class="input-box">
                                        <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                                    </div>
                                </div>
                            </li>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                        <!--  li class="control">
                            <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" <?php if ($_address->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                        </li -->
                    <?php else:?>
                        <!--  li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li -->
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                </ul>
            </fieldset>
        </li>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('checkout.onepage.billing.extra')?>
        <?php if (Mage::helper('firecheckout')->canShowNewsletter()) : ?>
            <li class="newsletter control">
                <input type="checkbox" id="newsletter-signup" name="newsletter" value="1"<?php if (Mage::getStoreConfig('firecheckout/general/newsletter_checkbox_state')) : ?> checked="checked"<?php endif; ?> title="<?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>" class="checkbox" /><label for="newsletter-signup"><?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?></label>
            </li>
        <?php endif; ?>
        <?php $additional = $this->getChildHtml('billing.additional.container');
        if (!empty($additional)) : ?>
            <li class="billing-additional">
                <?php echo $additional; ?>
            </li>
        <?php endif; ?>
        </ul>
    <?php if (!$this->canShip() || !Mage::getStoreConfig('firecheckout/general/shipping_address')): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php else: ?>
        <input type="hidden" name="billing[use_for_shipping]" id="billing:use_for_shipping" value="<?php if ($this->isUseBillingAddressForShipping()):?>1<?php else:?>0<?php endif; ?>" />
    <?php endif; ?>

    <script type="text/javascript">
        var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
		 Validation.add('validar_cpfcnpj', 'O CPF ou CNPJ informado \xE9 invalido', function(v){return validaCPF(v,0);});
	     Validation.add('postcode', 'Por favor digite 8 numeros. ', function( v ) {
     if (v.length >= 8 )
       return true;
     else
       return false;
    });
    //]]>


    </script>

    <script type="text/javascript">
    		jQuery(function(){
    		var postcode = 0;
    		jQuery("#billing-address .postcode").focusout(function(){
    			if(jQuery(this).val().length >= 8 &&  jQuery(this).val() != postcode)
    			{
    				buscacep('<?php echo Mage::getUrl("firecheckout/index/searchcep") ?>', {cep : jQuery(this).val()}, '<?php echo $_prefix ?>');
    				postcode = jQuery(this).val();
    			}
    		});

    	});

    </script>
    </div>
</div>
