<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <p><strong>Nós amamos</strong><br />
                fazer parte deste momento tão importante da sua vida. Ao criar a lista na EasyShopBrasil, você ganhará benefícios exclusivos.
                Selecionamos parceiros especiais para você ter vantagens, experiências únicas e tornar seu casamento inesquecível.</p>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('form_giftlist') ?>    
<script>
    jQuery(function(){

    	jQuery('#modal-create').on('click', function(event) {
    	    var target = jQuery('#box-form-geral');
    	    if( target.length ) {

    	        jQuery('html, body').stop().animate({
    	            scrollTop: jQuery('.bx-wrapper').outerHeight() + jQuery('#header').outerHeight() +100
    	        }, 1000);
    	    }

    		jQuery('#modal-create').hide();
            jQuery('#box-form-geral').slideDown().show();

    	});

    	jQuery('#box-form-geral').slideUp();


    });
</script>


