<div class="page-title">
	<h1><?php echo $this->__('Casamento de %s & %s', $this->getList()->getData('jbpgl_name_noivo'), $this->getList()->getData('jbpgl_name_noiva'))?></h1>
</div>

<div class="std"><p><?php echo $this->getList()->getData('jbpgl_description'); ?></p></div>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>

            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                        one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                        we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                        will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                        This $_imgSize value could even be decreased further, based on the page layout
                        (one column, two column, three column) and number of product columns. */ ?>
                <?php $_imgSize = 300; ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <div class="product-primary">
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                        <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                        <?php endif; ?>
                        <?php
                        // Provides extra blocks on which to hang some features for products in the list
                        // Features providing UI elements targeting this block will display directly below the product name
                        if ($this->getChild('name.after')) {
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
                                echo $_nameAfterChild->toHtml();
                            }
                        }
                        ?>
                    </div>
                    <div class="product-secondary">
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </div>
                    <div class="product-secondary">
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                            <p class="action"><button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <p class="action"><a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                        <?php else: ?>
                            <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <div class="best-caroussel">
        <div class="bx-wrapper">
            <div class="bx-viewport">
                        <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
                            <?php $i=0; foreach ($_productCollection as $_product): ?>
                                <?php /*if ($i++%$_columnCount==0): ?>
                                <?php endif*/ ?>
                                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">

                        			<?php

                        			    $idList = (int)Mage::app()->getRequest()->getParam('id');

                                        $urlProduct = $_product->getUrlModel()->getUrl($_product, array('_query' => array(
                                            'listcasamento' => $idList
                                        )));

                                    ?>

                                    <div class="box-principal">
                                	     <div class="box-content">
                                            <a href="<?php echo $urlProduct ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                                <?php $_imgSize = 210; ?>
                                                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(170,170); ?>"
                                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                            </a>
                                	    </div>
                                    	<a href="<?php echo $urlProduct ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>">
                                		  <div class="border-skew"></div>
                                		</a>
                                	</div>


                                        <div class="box-slider-price">
                                            <a href="<?php echo $urlProduct ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>">
                                                <?php echo $this->getPriceHtml($_product, true) ?>
                                                <div class="border-skew-price"></div>
                                            </a>
                                        </div>

                                        <div class="payment">
                                            <span>ou 10x de <?php echo Mage::helper('trendsclub_theme')->getLastParcela($_product->getFinalPrice())?></span>
                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                <a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="xicon-heart">
                                                    <i class="fa fa-heart-o" aria-hidden="true"></i>
                                                </a>
                                            <?php endif; ?>
                                        </div>

                                        <div class="box-master-actions">

                                            <h2 class="product-name">
                                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>">
                                        	   <?php
                                        	       echo (strlen($this->escapeHtml($_product->getName())) > 80) ? substr($this->escapeHtml($_product->getName()), 0 ,80 ).' ...': substr($this->escapeHtml($_product->getName()), 0 ,80 );
                                        	   ?>
                                    	   </a>
                                                <!--  a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                                    <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                                </a-->
                                            </h2>

                                            <?php
                                            // Provides extra blocks on which to hang some features for products in the list
                                            // Features providing UI elements targeting this block will display directly below the product name
                                            if ($this->getChild('name.after')) {
                                                $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                                foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                                    $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                                    $_nameAfterChild->setProduct($_product);
                                                    echo $_nameAfterChild->toHtml();
                                                }
                                            }
                                            ?>
                                            <?php //echo $this->getPriceHtml($_product, true) ?>
                                            <?php if($_product->getRatingSummary()): ?>
                                            <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                            <?php endif; ?>

                                            <div class="actions">

                                                <?php if(!in_array($_product->getId(), $this->getBlockGiftList()->getAllIdOfProductsReceivedPublic())):?>

                                                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                                                        	<?php $idList = Mage::app()->getRequest()->getParam('id')?>
                                                            <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product,array('listcasamento'=> $idList)) ?>')">
                                                                <span>
                                                                    <span class="ico-cart"></span>
                                                                </span>
                                                            </button>
                                                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>

                                                                <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button btn-cart" href="<?php echo $_product->getProductUrl() ?>">
                                                                    <span>
                                                                        <img src="<?php echo $this->getSkinUrl('images/lupinha.png')?>" />
                                                                    </span>
                                                                </a>

                                                        <?php else: ?>
                                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                                        <?php endif; ?>
                                                        <!--<ul class="add-to-links">
                                                             <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                                            <?php endif; ?>
                                                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                                            <?php endif; ?>
                                                        </ul> -->

                                                <?php else: ?>
                                                        <p class="availability out-of-stock"><span><?php echo $this->__('comprado') ?></span></p>
                                                <?php endif; ?>
                                            </div>

                                        </div>


                                </li>
                                <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                                <?php endif*/ ?>
                            <?php endforeach ?>
                        </ul>
            </div>
        </div>
    </div>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom" style="display: none">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>

<script>
  jQuery(function(){
	    jQuery('a.col-4').click(function(){
	    	jQuery('ul.products-grid').addClass('products-grid--max-4-col');
	    	jQuery('ul.products-grid').removeClass('products-grid--max-3-col products-grid--max-2-col');
	    	return false;
	    });


	    jQuery('a.col-3').click(function(){
	    	jQuery('ul.products-grid').addClass('products-grid--max-3-col');
	    	jQuery('ul.products-grid').removeClass('products-grid--max-4-col products-grid--max-2-col');
	    	return false;
	    });

	    jQuery('a.col-2').click(function(){
	    	jQuery('ul.products-grid').addClass('products-grid--max-2-col');
	    	jQuery('ul.products-grid').removeClass('products-grid--max-3-col products-grid--max-4-col');
	    	return false;
	    });
  });
</script>

