<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-56dd7d6afdd6cc97"></script>
<div 
	class="addthis_sharing_toolbox" 
	data-url="<?php echo $this->getUrl('listaCasamento/index/listaCasamentoProdutos/', array('id'=>$this->getListByCustomer()->getData('jbpgl_id')))?> " 
	data-title="Lista de casamento de <?php echo $this->getListByCustomer()->getData('jbpgl_name_noivo').' & '. $this->getListByCustomer()->getData('jbpgl_name_noiva')?>"></div>