<?php
    $_productCollection=$this->setProductCollection();
    $_helper = $this->helper('catalog/output');
    $_block = $this->getBlockGiftList();
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('Você ainda não adicionou nenhum produto para a sua lista') ?></p>
<?php else: ?>

<div class="best-caroussel">
	<div class="bx-wrapper">
		<div class="bx-viewport">
	

<div id="category-products-giftlist" class="category-products">
    <?php // Grid Mode ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <ul class="products-grid products-grid-giftlist products-grid--max-<?php echo $_columnCount; ?>-col">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <?php /*if ($i++%$_columnCount==0): ?>
            <?php endif*/ ?>
            
                    <li class=" item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> disabled-li">
        
        				<div class="box-principal">
                    	     <div class="box-content">
                                <a href="javascript:void(0)" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                    <?php $_imgSize = 180; ?>
                                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                </a>
                             </div>
                        	 <a href="javascript:void(0)" title="<?php echo $this->escapeHtml($_product->getName()) ?>">
                    		 	 <div class="border-skew">
 	                    		<?php if(in_array($_product->getId(), $this->getProductsRansomed()) && $this->getRequest()->getParam('item')): ?>
 	                    			<span class="mark-l resgatado-gf">
 	                    				<span>Resgatado</span>
                    				</span>
 	                    		<?php endif;?>
 	                    		<?php if(in_array($_product->getId(), $this->getBlockGiftList()->getAllIdOfProductsReceived(array('credito_lista_casamento'))) && $this->getRequest()->getParam('item')): ?>
 	                    			<span class="mark-l recebido-gf">
                    					<span>Recebido</span>
                    				</span>
 	                    		<?php endif;?>
                    		 	 </div>
                    		 </a>
                    	</div>
                    	
                    	<div class="box-slider-price">
                            <a href="javascript:void(0)" title="<?php echo $this->escapeHtml($_product->getName()) ?>">
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <span class="label-frete">mais frete</span>
                                <div class="border-skew-price"></div>
                            </a>
                        </div>
                    	    
                         <div class="box-master-actions">
                            <h2 class="product-name">
                            	<a href="javascript:void(0)" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                            		<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                        		</a>
                            </h2>
                            <?php
                            // Provides extra blocks on which to hang some features for products in the list
                            // Features providing UI elements targeting this block will display directly below the product name
                            if ($this->getChild('name.after')) {
                                $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                    $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                    $_nameAfterChild->setProduct($_product);
                                    echo $_nameAfterChild->toHtml();
                                }
                            }
                            ?>
                            
                            <?php if($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php endif; ?>
                            
                         </div>

                    </li>
            <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            <?php endif*/ ?>
        <?php endforeach ?>

    </ul>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

	

</div>
		</div>
	</div>
</div>

