<?php $_product = $this->getProduct(); ?>
<div class="container-button-prov">
    <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart"
    onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product, array('prova'=>1)) ?>','<?php echo $_product->getId()?>')">
        <span>
            <span><?php echo $this->__('PROVAR') ?></span>
        </span>
    </button>
</div>
